The Totals, Per 100 Poss, and Advanced pages are fairly similar. Play by Play and Shooting Data have two headers. This Jupyter Notebook will be the testing environment on how to transform the data.

In [33]:
# Import Dependencies
from selenium import webdriver 
import pandas as pd 
from StatPuts import username, password

In [123]:
# Log-in to BKRef
login_address = 'https://stathead.com/users/login.cgi?token=1&redirect_uri=https%3A//www.basketball-reference.com/leagues/NBA_2020_totals.html'
browser = webdriver.Chrome(executable_path=r'chromedriver.exe')
browser.get(login_address)
#Fill in the form with username and password
user_name = browser.find_element_by_id('username')
user_name.send_keys(username)
pass_word = browser.find_element_by_id('password')
pass_word.send_keys(password)
#Click the login button
browser.find_element_by_id('login').submit()

### Test Play-by-Play

In [3]:
url = 'https://www.basketball-reference.com/leagues/NBA_2018_play-by-play.html'
browser.get(url)

In [26]:
year_df = pd.read_html(url)[0]
year_df

    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk             Player                Pos
0                    1       √Ålex Abrines                 SG
1                    2         Quincy Acy                 PF
2                    3       Steven Adams                  C
3                    4        Bam Adebayo                  C
4                    5      Arron Afflalo                 SG
..                 ...                ...                ...
685                537       Tyler Zeller                  C
686                537       Tyler Zeller                  C
687                538        Paul Zipser                 SF
688                539         Ante ≈Ωi≈æiƒá                  C
689                540        Ivica Zubac                  C

    Unnamed: 3_level_0 Unnamed: 4_level_0 Totals       Position Estimate       \
                   Age                 Tm      G    MP               PG%  SG%
0                   24                OKC     75  1134                5%  90%
1                   27                BRK     70  1359               NaN  NaN
2                   24                OKC     76  2487               NaN  NaN
3                   20                MIA     69  1368               NaN  NaN
4                   32                ORL     53   682                5%  77%
..                 ...                ...    ...   ...               ...  ...
685                 28                BRK     42   703               NaN  NaN
686                 28                MIL     24   406               NaN  NaN
687                 23                CHI     54   824               NaN  NaN
688                 21                CLE     32   214               NaN  NaN
689                 20                LAL     43   410               NaN  NaN

          ... +/- Per 100 Poss. Turnovers          Fouls Committed       \
     SF%  ...            On-Off   BadPass LostBall           Shoot Off.
0     5%  ...              -4.4        14        7              66    1
1    NaN  ...               1.8        21       13              63   15
2    NaN  ...               6.8        26       34              75   41
3    NaN  ...              -0.7        16       24              62   18
4    18%  ...              -1.6        10        3              31    4
..   ...  ...               ...       ...      ...             ...  ...
685  NaN  ...               3.8         6       13              42   10
686  NaN  ...               3.6         4        2              30    5
687  51%  ...              -6.5        15       12              38    6
688  NaN  ...              -7.8         3        3              20    2
689  NaN  ...               6.2         8       11              25    5

    Fouls Drawn      Misc.
          Shoot Off.   PGA And1 Blkd
0            15    3    66    4    9
1            20    9   145    1   13
2           112    4   213   32   47
3            81   10   260   19   29
4            11    2    76    0    8
..          ...  ...   ...  ...  ...
685          31    1    72   14   24
686           8    1    46    2   10
687          10    3   115    0   14
688          13    1    12    4    2
689          22    0    58    3   12

[690 rows x 23 columns]

In [105]:
year_df.columns.levels[0]

Index(['+/- Per 100 Poss.', 'Fouls Committed', 'Fouls Drawn', 'Misc.',
       'Position Estimate', 'Totals', 'Turnovers', 'Unnamed: 0_level_0',
       'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Unnamed: 3_level_0',
       'Unnamed: 4_level_0'],
      dtype='object')

In [27]:
year_df.columns = year_df.columns.droplevel()

In [6]:
year_df

,Rk,Player,Pos,Age,Tm,G,MP,PG%,SG%,SF%,...,On-Off,BadPass,LostBall,Shoot,Off.,Shoot,Off.,PGA,And1,Blkd
0,1,√Ålex Abrines,SG,24,OKC,75,1134,5%,90%,5%,...,-4.4,14,7,66,1,15,3,66,4,9
1,2,Quincy Acy,PF,27,BRK,70,1359,NaN,NaN,NaN,...,1.8,21,13,63,15,20,9,145,1,13
2,3,Steven Adams,C,24,OKC,76,2487,NaN,NaN,NaN,...,6.8,26,34,75,41,112,4,213,32,47
3,4,Bam Adebayo,C,20,MIA,69,1368,NaN,NaN,NaN,...,-0.7,16,24,62,18,81,10,260,19,29
4,5,Arron Afflalo,SG,32,ORL,53,682,5%,77%,18%,...,-1.6,10,3,31,4,11,2,76,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,537,Tyler Zeller,C,28,BRK,42,703,NaN,NaN,NaN,...,3.8,6,13,42,10,31,1,72,14,24
686,537,Tyler Zeller,C,28,MIL,24,406,NaN,NaN,NaN,...,3.6,4,2,30,5,8,1,46,2,10
687,538,Paul Zipser,SF,23,CHI,54,824,NaN,NaN,51%,...,-6.5,15,12,38,6,10,3,115,0,14
688,539,Ante ≈Ωi≈æiƒá,C,21,CLE,32,214,NaN,NaN,NaN,...,-7.8,3,3,20,2,13,1,12,4,2
689,540,Ivica Zubac,C,20,LAL,43,410,NaN,NaN,NaN,...,6.2,8,11,25,5,22,0,58,3,12

In [28]:
# Change columns with multiple names (Shoot, Off.)
cols = []
scount, ocount = 1, 1
for column in year_df.columns:
    if column == 'Shoot':
        cols.append(f'Shoot_{scount}')
        scount+=1
        continue
    elif column == 'Off.':
        cols.append(f'Off_{ocount}')
        ocount+=1
        continue
    cols.append(column)
year_df.columns = cols

In [29]:
year_df = year_df.rename(columns={
    'OnCourt':'PMP100_OnCourt',
    'On-Off':'PMP100_On_Off',
    'BadPass': 'BadPassTO',
    'LostBall': 'LostBallTO',
    'Shoot_1': 'FoulC_Shoot',
    'Shoot_2': 'FoulD_Shoot',
    'Off_1': 'FoulC_Off',
    'Off_2': 'FoulD_Off',
})
year_df

,Rk,Player,Pos,Age,Tm,G,MP,PG%,SG%,SF%,...,PMP100_On_Off,BadPassTO,LostBallTO,FoulC_Shoot,FoulC_Off,FoulD_Shoot,FoulD_Off,PGA,And1,Blkd
0,1,√Ålex Abrines,SG,24,OKC,75,1134,5%,90%,5%,...,-4.4,14,7,66,1,15,3,66,4,9
1,2,Quincy Acy,PF,27,BRK,70,1359,NaN,NaN,NaN,...,1.8,21,13,63,15,20,9,145,1,13
2,3,Steven Adams,C,24,OKC,76,2487,NaN,NaN,NaN,...,6.8,26,34,75,41,112,4,213,32,47
3,4,Bam Adebayo,C,20,MIA,69,1368,NaN,NaN,NaN,...,-0.7,16,24,62,18,81,10,260,19,29
4,5,Arron Afflalo,SG,32,ORL,53,682,5%,77%,18%,...,-1.6,10,3,31,4,11,2,76,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,537,Tyler Zeller,C,28,BRK,42,703,NaN,NaN,NaN,...,3.8,6,13,42,10,31,1,72,14,24
686,537,Tyler Zeller,C,28,MIL,24,406,NaN,NaN,NaN,...,3.6,4,2,30,5,8,1,46,2,10
687,538,Paul Zipser,SF,23,CHI,54,824,NaN,NaN,51%,...,-6.5,15,12,38,6,10,3,115,0,14
688,539,Ante ≈Ωi≈æiƒá,C,21,CLE,32,214,NaN,NaN,NaN,...,-7.8,3,3,20,2,13,1,12,4,2
689,540,Ivica Zubac,C,20,LAL,43,410,NaN,NaN,NaN,...,6.2,8,11,25,5,22,0,58,3,12

In [13]:
year_df.keys()

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'PG%', 'SG%', 'SF%',
       'PF%', 'C%', 'PMP100_OnCourt', 'PMP100_On_Off', 'BadPassTO',
       'LostBallTO', 'FoulC_Shoot', 'FoulC_Off', 'FoulD_Shoot', 'FoulD_Off',
       'PGA', 'And1', 'Blkd'],
      dtype='object')

In [30]:
year_df = year_df.loc[year_df["Rk"] != "Rk"]
text_keys = ['Player','Pos','Tm']
keys_list = year_df.keys()
num_keys = []
for key in keys_list:
    if key not in text_keys:
        num_keys.append(key)
for key in num_keys:
    try:
        year_df[key] = pd.to_numeric(year_df[key])
    except:
        year_df[key] = pd.to_numeric(year_df[key].replace('\%','',regex=True))/100

<ipython-input-30-e7be2e0da30a>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_df[key] = pd.to_numeric(year_df[key])
<ipython-input-30-e7be2e0da30a>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_df[key] = pd.to_numeric(year_df[key].replace('\%','',regex=True))/100

In [31]:
year_df.dtypes

Rk                  int64
Player             object
Pos                object
Age                 int64
Tm                 object
G                   int64
MP                  int64
PG%               float64
SG%               float64
SF%               float64
PF%               float64
C%                float64
PMP100_OnCourt    float64
PMP100_On_Off     float64
BadPassTO           int64
LostBallTO          int64
FoulC_Shoot         int64
FoulC_Off           int64
FoulD_Shoot         int64
FoulD_Off           int64
PGA                 int64
And1                int64
Blkd                int64
dtype: object

### Need to transfrom Position % to number before converting column data type

In [32]:
year_df

,Rk,Player,Pos,Age,Tm,G,MP,PG%,SG%,SF%,...,PMP100_On_Off,BadPassTO,LostBallTO,FoulC_Shoot,FoulC_Off,FoulD_Shoot,FoulD_Off,PGA,And1,Blkd
0,1,√Ålex Abrines,SG,24,OKC,75,1134,0.05,0.90,0.05,...,-4.4,14,7,66,1,15,3,66,4,9
1,2,Quincy Acy,PF,27,BRK,70,1359,NaN,NaN,NaN,...,1.8,21,13,63,15,20,9,145,1,13
2,3,Steven Adams,C,24,OKC,76,2487,NaN,NaN,NaN,...,6.8,26,34,75,41,112,4,213,32,47
3,4,Bam Adebayo,C,20,MIA,69,1368,NaN,NaN,NaN,...,-0.7,16,24,62,18,81,10,260,19,29
4,5,Arron Afflalo,SG,32,ORL,53,682,0.05,0.77,0.18,...,-1.6,10,3,31,4,11,2,76,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,537,Tyler Zeller,C,28,BRK,42,703,NaN,NaN,NaN,...,3.8,6,13,42,10,31,1,72,14,24
686,537,Tyler Zeller,C,28,MIL,24,406,NaN,NaN,NaN,...,3.6,4,2,30,5,8,1,46,2,10
687,538,Paul Zipser,SF,23,CHI,54,824,NaN,NaN,0.51,...,-6.5,15,12,38,6,10,3,115,0,14
688,539,Ante ≈Ωi≈æiƒá,C,21,CLE,32,214,NaN,NaN,NaN,...,-7.8,3,3,20,2,13,1,12,4,2
689,540,Ivica Zubac,C,20,LAL,43,410,NaN,NaN,NaN,...,6.2,8,11,25,5,22,0,58,3,12

In [10]:
perc_list = ["PG%","SG%","SF%","PF%","C%"]
for col in perc_list:
    year_df[col] = pd.to_numeric(year_df[col].replace('\%','',regex=True))/100
    #year_df.loc[:, col] = col_fixer
# pd.to_numeric(year_df["PG%"].replace('\%','',regex=True))/100
# pd.to_numeric(year_df["SG%"].replace('\%','',regex=True))/100
# pd.to_numeric(year_df["SF%"].replace('\%','',regex=True))/100
# pd.to_numeric(year_df["PF%"].replace('\%','',regex=True))/100
# pd.to_numeric(year_df["C%"].replace('\%','',regex=True))/100

### transformed above using try/except block

<ipython-input-10-f928768182c6>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_df[col] = pd.to_numeric(year_df[col].replace('\%','',regex=True))/100

In [33]:
del year_df

### Test Shooting

In [34]:
url = 'https://www.basketball-reference.com/leagues/NBA_2018_shooting.html'
browser.get(url)

In [73]:
year_df = pd.read_html(url, header = 1)[0]
year_df = year_df.loc[year_df["Rk"] != "Rk"]
year_df

,Rk,Player,Pos,Age,Tm,G,MP,FG%,Dist.,Unnamed: 9,...,3P.2,Unnamed: 26,%FGA,#,Unnamed: 29,%3PA,3P%,Unnamed: 32,Att.,#.1
0,1,√Ålex Abrines,SG,24,OKC,75,1134,.395,20.3,NaN,...,1.000,NaN,.034,9,NaN,.253,.375,NaN,1,0
1,2,Quincy Acy,PF,27,BRK,70,1359,.356,20.7,NaN,...,.990,NaN,.036,9,NaN,.305,.404,NaN,0,0
2,3,Steven Adams,C,24,OKC,76,2487,.629,2.6,NaN,...,NaN,NaN,.242,150,NaN,.000,NaN,NaN,2,0
3,4,Bam Adebayo,C,20,MIA,69,1368,.512,4.3,NaN,...,NaN,NaN,.294,91,NaN,.000,NaN,NaN,4,0
4,5,Arron Afflalo,SG,32,ORL,53,682,.401,17.1,NaN,...,.926,NaN,.000,0,NaN,.414,.276,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,537,Tyler Zeller,C,28,BRK,42,703,.546,6.0,NaN,...,1.000,NaN,.039,7,NaN,.731,.526,NaN,0,0
686,537,Tyler Zeller,C,28,MIL,24,406,.590,3.4,NaN,...,NaN,NaN,.086,8,NaN,1.000,.000,NaN,0,0
687,538,Paul Zipser,SF,23,CHI,54,824,.346,16.9,NaN,...,.973,NaN,.026,6,NaN,.209,.391,NaN,0,0
688,539,Ante ≈Ωi≈æiƒá,C,21,CLE,32,214,.731,3.4,NaN,...,NaN,NaN,.149,10,NaN,NaN,NaN,NaN,0,0
689,540,Ivica Zubac,C,20,LAL,43,410,.500,3.8,NaN,...,NaN,NaN,.189,19,NaN,.000,NaN,NaN,0,0

In [63]:
year_df.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'FG%', 'Dist.',
       'Unnamed: 9', '2P', '0-3', '3-10', '10-16', '16-3P', '3P',
       'Unnamed: 16', '2P.1', '0-3.1', '3-10.1', '10-16.1', '16-3P.1', '3P.1',
       'Unnamed: 23', '2P.2', '3P.2', 'Unnamed: 26', '%FGA', '#',
       'Unnamed: 29', '%3PA', '3P%', 'Unnamed: 32', 'Att.', '#.1'],
      dtype='object')

In [74]:
cols = [c for c in year_df.columns if c.lower()[:7] != 'unnamed']
cols

['Rk',
 'Player',
 'Pos',
 'Age',
 'Tm',
 'G',
 'MP',
 'FG%',
 'Dist.',
 '2P',
 '0-3',
 '3-10',
 '10-16',
 '16-3P',
 '3P',
 '2P.1',
 '0-3.1',
 '3-10.1',
 '10-16.1',
 '16-3P.1',
 '3P.1',
 '2P.2',
 '3P.2',
 '%FGA',
 '#',
 '%3PA',
 '3P%',
 'Att.',
 '#.1']

In [75]:
year_df = year_df[cols]
year_df

,Rk,Player,Pos,Age,Tm,G,MP,FG%,Dist.,2P,...,16-3P.1,3P.1,2P.2,3P.2,%FGA,#,%3PA,3P%,Att.,#.1
0,1,√Ålex Abrines,SG,24,OKC,75,1134,.395,20.3,.241,...,.083,.380,.548,1.000,.034,9,.253,.375,1,0
1,2,Quincy Acy,PF,27,BRK,70,1359,.356,20.7,.200,...,.333,.349,.857,.990,.036,9,.305,.404,0,0
2,3,Steven Adams,C,24,OKC,76,2487,.629,2.6,.997,...,.000,.000,.690,NaN,.242,150,.000,NaN,2,0
3,4,Bam Adebayo,C,20,MIA,69,1368,.512,4.3,.979,...,.214,.000,.701,NaN,.294,91,.000,NaN,4,0
4,5,Arron Afflalo,SG,32,ORL,53,682,.401,17.1,.568,...,.281,.386,.632,.926,.000,0,.414,.276,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,537,Tyler Zeller,C,28,BRK,42,703,.546,6.0,.886,...,.444,.385,.757,1.000,.039,7,.731,.526,0,0
686,537,Tyler Zeller,C,28,MIL,24,406,.590,3.4,.981,...,.250,.000,.758,NaN,.086,8,1.000,.000,0,0
687,538,Paul Zipser,SF,23,CHI,54,824,.346,16.9,.530,...,.209,.336,.591,.973,.026,6,.209,.391,0,0
688,539,Ante ≈Ωi≈æiƒá,C,21,CLE,32,214,.731,3.4,1.000,...,1.000,NaN,.633,NaN,.149,10,NaN,NaN,0,0
689,540,Ivica Zubac,C,20,LAL,43,410,.500,3.8,.992,...,.000,.000,.656,NaN,.189,19,.000,NaN,0,0

In [76]:
year_df.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'FG%', 'Dist.', '2P',
       '0-3', '3-10', '10-16', '16-3P', '3P', '2P.1', '0-3.1', '3-10.1',
       '10-16.1', '16-3P.1', '3P.1', '2P.2', '3P.2', '%FGA', '#', '%3PA',
       '3P%', 'Att.', '#.1'],
      dtype='object')

In [77]:
year_df = year_df.rename(columns={
    '2P':'2P_FGAxDist',
    '0-3':'0_3_FGAxDist',
    '3-10':'3_10_FGAxDist', 
    '10-16':'10_16_FGAxDist', 
    '16-3P':'16_3P_FGAxDist', 
    '3P':'3P_FGAxDist', 
    '2P.1':'2P_FGPxDist', 
    '0-3.1':'0_3_FGPxDist', 
    '3-10.1':'3_10_FGPxDist',
    '10-16.1':'10_16_FGPxDist', 
    '16-3P.1':'16_3P_FGPxDist', 
    '3P.1':'3P_FGPxDist', 
    '2P.2':'2PAstP', 
    '3P.2':'3PAstP', 
    '%FGA':'Dunks_FGA', 
    '#':'Num_Dunks', 
    '%3PA':'Corner_3PFGA',
    '3P%':'Corner_3PP', 
    'Att.':'Heaves_Att', 
    '#.1':'Heaves_Made',
})
year_df

,Rk,Player,Pos,Age,Tm,G,MP,FG%,Dist.,2P_FGAxDist,...,16_3P_FGPxDist,3P_FGPxDist,2PAstP,3PAstP,Dunks_FGA,Num_Dunks,Corner_3PFGA,Corner_3PP,Heaves_Att,Heaves_Made
0,1,√Ålex Abrines,SG,24,OKC,75,1134,.395,20.3,.241,...,.083,.380,.548,1.000,.034,9,.253,.375,1,0
1,2,Quincy Acy,PF,27,BRK,70,1359,.356,20.7,.200,...,.333,.349,.857,.990,.036,9,.305,.404,0,0
2,3,Steven Adams,C,24,OKC,76,2487,.629,2.6,.997,...,.000,.000,.690,NaN,.242,150,.000,NaN,2,0
3,4,Bam Adebayo,C,20,MIA,69,1368,.512,4.3,.979,...,.214,.000,.701,NaN,.294,91,.000,NaN,4,0
4,5,Arron Afflalo,SG,32,ORL,53,682,.401,17.1,.568,...,.281,.386,.632,.926,.000,0,.414,.276,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,537,Tyler Zeller,C,28,BRK,42,703,.546,6.0,.886,...,.444,.385,.757,1.000,.039,7,.731,.526,0,0
686,537,Tyler Zeller,C,28,MIL,24,406,.590,3.4,.981,...,.250,.000,.758,NaN,.086,8,1.000,.000,0,0
687,538,Paul Zipser,SF,23,CHI,54,824,.346,16.9,.530,...,.209,.336,.591,.973,.026,6,.209,.391,0,0
688,539,Ante ≈Ωi≈æiƒá,C,21,CLE,32,214,.731,3.4,1.000,...,1.000,NaN,.633,NaN,.149,10,NaN,NaN,0,0
689,540,Ivica Zubac,C,20,LAL,43,410,.500,3.8,.992,...,.000,.000,.656,NaN,.189,19,.000,NaN,0,0

In [78]:
del year_df

### Adusted shooting
- In addition to a multi-index, there seems to be a footer every 20 rows in addition to the rank

In [8]:
url = 'https://www.basketball-reference.com/leagues/NBA_2018_adj_shooting.html'
browser.get(url)

In [ ]:
year_df = pd.read_html(url)
#year_df = year_df.loc[year_df["Rk"] != "Rk"]
year_df
browser.quit()

Data not stored in table form, however, player shooting fields can be found in other data we have, and league adjusted amounts can be calculated.

## Let's try created per 36/per game data

In [22]:
test = pd.DataFrame({
    'Player': ['A', 'B'],
    "GP": [5, 10],
    'Stat': [100, 200],
    'StatB': [25, 30],
    'StatC': [.345,.765]
    
})

test

  Player  GP  Stat  StatB  StatC
0      A   5   100     25  0.345
1      B  10   200     30  0.765

In [23]:
num_keys = ['Stat', 'StatB']
for key in num_keys:
    if test[key].dtype == 'int64':
        test[key] = test[key]/test['GP']
# test['Stat'] = test['Stat']/test['GP']
test

  Player  GP  Stat  StatB  StatC
0      A   5  20.0    5.0  0.345
1      B  10  20.0    3.0  0.765

## Handling multiple exceptions same type

In [31]:
try:
    from StatPuts import d_type, p_type
except ImportError as err:
    if 'p_type' in ("{0}".format(err)):
        print('True')

True

## Try getting unique player codes

In [35]:
from bs4 import BeautifulSoup as bs

In [40]:
html = browser.page_source
soup = bs(html, "html.parser")

In [99]:
results = soup.find('td', class_='left')

In [100]:
results.attrs['data-append-csv']

'adamsst01'

In [101]:
results = soup.find_all('td', class_='left')

In [105]:
player_ids = []
for result in results:
    try:
        if result.attrs['data-append-csv'] not in player_ids:
            player_ids.append(result.attrs['data-append-csv'])
    except:
        pass

In [109]:
print(len(player_ids))
player_ids

529

['adamsst01',
 'adebaba01',
 'aldrila01',
 'alexaky01',
 'alexani01',
 'allengr01',
 'allenja01',
 'allenka01',
 'aminual01',
 'anderju01',
 'anderky01',
 'anderry01',
 'antetgi01',
 'antetko01',
 'antetth01',
 'anthoca01',
 'anunoog01',
 'arcidry01',
 'arizatr01',
 'augusdj01',
 'aytonde01',
 'bacondw01',
 'baglema01',
 'balllo01',
 'bambamo01',
 'bareajo01',
 'barneha02',
 'barrerj01',
 'bartowi01',
 'bateske01',
 'batumni01',
 'baynear01',
 'bazemke01',
 'bazleda01',
 'bealbr01',
 'beaslma01',
 'belinma01',
 'belljo01',
 'bembrde01',
 'bendedr01',
 'bertada01',
 'beverpa01',
 'birchkh01',
 'bitadgo01',
 'biyombi01',
 'bjeline01',
 'bledser01',
 'bogdabo01',
 'bogdabo02',
 'bolbo01',
 'boldejo01',
 'boldema01',
 'bonejo01',
 'bongais01',
 'bookede01',
 'bouchch01',
 'bowenbr02',
 'bowmaky01',
 'bradlav01',
 'bradlto01',
 'brantja01',
 'brazdig01',
 'breweco01',
 'bridgmi01',
 'bridgmi02',
 'brissos01',
 'broekry01',
 'brogdma01',
 'brookdi01',
 'brownbr01',
 'brownch02',
 'brownja02',
 'brownmo01',
 'brownst02',
 'browntr01',
 'brunsja01',
 'bryanth01',
 'bullore01',
 'burketr01',
 'burksal01',
 'burtode02',
 'butleji01',
 'cabocbr01',
 'cacokde01',
 'caldwke01',
 'cancavl01',
 'capelca01',
 'carrode01',
 'carteje01',
 'cartevi01',
 'cartewe01',
 'cartemi01',
 'carusal01',
 'caulewi01',
 'chandty01',
 'chandwi01',
 'chealjo01',
 'cheatzy01',
 'chiozch01',
 'chrisma01',
 'clarkga01',
 'clarkbr01',
 'clarkjo01',
 'claxtni01',
 'clemoch01',
 'clevean01',
 'coffeam01',
 'collijo01',
 'colliza01',
 'conlemi01',
 'connapa01',
 'cookqu01',
 'cookty01',
 'covinro01',
 'crabbal01',
 'craigto01',
 'crawfja01',
 'crowdja01',
 'culveja01',
 'curryse01',
 'curryst01',
 'danietr01',
 'davisan02',
 'davised01',
 'daviste02',
 'dedmode01',
 'dellama01',
 'derozde01',
 'diallch01',
 'diallha01',
 'dienggo01',
 'dinwisp01',
 'divindo01',
 'doncilu01',
 'dortlu01',
 'dotsoda01',
 'doumbse01',
 'doziepj01',
 'dragigo01',
 'drumman01',
 'dudleja01',
 'dunnkr01',
 'edwarca01',
 'ellenhe01',
 'ellinwa01',
 'embiijo01',
 'ennisja01',
 'eubandr01',
 'evansja02',
 'exumda01',
 'fallta01',
 'favorde01',
 'feliccr01',
 'fergute01',
 'fernabr01',
 'ferreyo01',
 'finnedo01',
 'forbebr01',
 'fournev01',
 'foxde01',
 'frazime01',
 'frazimi01',
 'fraziti01',
 'fultzma01',
 'gabriwe01',
 'gaffoda01',
 'gallida01',
 'gallola01',
 'garlada01',
 'gasolma01',
 'gayru01',
 'georgpa01',
 'gibsota01',
 'gilesha01',
 'gilgesh01',
 'goberru01',
 'goodwbr01',
 'gordoaa01',
 'gordoer01',
 'grahade01',
 'grahatr01',
 'grantje01',
 'grantje02',
 'grayjo01',
 'greenda02',
 'greendr01',
 'greenja01',
 'greenja02',
 'greenje02',
 'griffbl01',
 'gudurma01',
 'guyky01',
 'hachiru01',
 'hallde01',
 'halldo01',
 'hannadu01',
 'hardati02',
 'hardeja01',
 'harklma01',
 'harpeja01',
 'harremo01',
 'harriga01',
 'harrijo01',
 'harrito02',
 'harrish01',
 'hartjo01',
 'harteis01',
 'hasleud01',
 'hayesja02',
 'haywago01',
 'hensojo01',
 'hernade01',
 'hernaju01',
 'hernawi01',
 'herroty01',
 'herveke01',
 'hezonma01',
 'hieldbu01',
 'hillge01',
 'hillso01',
 'hoardja01',
 'holidaa01',
 'holidjr01',
 'holidju01',
 'holliro01',
 'holmeri01',
 'hoodro01',
 'horfoal01',
 'hortota01',
 'houseda01',
 'howardw01',
 'howarwi01',
 'huertke01',
 'huntede01',
 'hutchch01',
 'ibakase01',
 'iguodan01',
 'ilyaser01',
 'inglejo01',
 'ingrabr01',
 'irvinky01',
 'isaacjo01',
 'iwundwe01',
 'jacksfr01',
 'jacksja02',
 'jacksjo02',
 'jacksju01',
 'jacksre01',
 'jamesju01',
 'jamesle01',
 'jeffeam01',
 'jeffrda01',
 'jeromty01',
 'johnsal02',
 'johnsbj01',
 'johnsca02',
 'johnsja01',
 'johnske04',
 'johnsst04',
 'johnsty01',
 'jokicni01',
 'jonesda03',
 'jonesde02',
 'jonesty01',
 'jordade01',
 'josepco01',
 'kabenmf01',
 'kaminfr01',
 'kanteen01',
 'kennalu01',
 'kiddst01',
 'kiddgmi01',
 'kinglo02',
 'klebima01',
 'knighbr03',
 'knoxke01',
 'konchjo01',
 'korkmfu01',
 'kornelu01',
 'korveky01',
 'kurucro01',
 'kuzmaky01',
 'labissk01',
 'lambje01',
 'langfro01',
 'lavinza01',
 'lawvi01',
 'laymaja01',
 'leaftj01',
 'lecquja01',
 'leeco01',
 'leeda03',
 'lenal01',
 'leonaka01',
 'leoname01',
 'leverca01',
 'lillada01',
 'littlna01',
 'looneke01',
 'lopezbr01',
 'lopezro01',
 'loveke01',
 'lowryky01',
 'luwawti01',
 'lylestr01',
 'maconda01',
 'macurjp01',
 'magetjo01',
 'mahinia01',
 'makerth01',
 'mannte01',
 'marjabo01',
 'markkla01',
 'martica02',
 'martico01',
 'martije02',
 'martike03',
 'masonfr01',
 'mathega01',
 'matthwe02',
 'mbahalu01',
 'mccawpa01',
 'mccolcj01',
 'mccontj01',
 'mcdanja01',
 'mcderdo01',
 'mcgeeja01',
 'mcgruro01',
 'mckinal01',
 'mclaujo01',
 'mclembe01',
 'mcraejo01',
 'mellini01',
 'meltode01',
 'metuch01',
 'middlkh01',
 'mikaer01',
 'milescj01',
 'millema01',
 'millspa02',
 'millspa01',
 'miltosh01',
 'mitchdo01',
 'mitrona01',
 'mokokad01',
 'monkma01',
 'moonema01',
 'mooreet01',
 'moranja01',
 'morgaju01',
 'morrima03',
 'morrima02',
 'morrimo01',
 'motlejo01',
 'mudiaem01',
 'muldemy01',
 'murrade01',
 'murraja01',
 'musadz01',
 'muscami01',
 'mykhasv01',
 'naderab01',
 'nancela02',
 'napiesh01',
 'netora01',
 'newmama01',
 'niangge01',
 'noahjo01',
 'noelne01',
 'norveza01',
 'nowelja01',
 'ntilila01',
 'nunnke01',
 'nurkiju01',
 'nwabada01',
 'onealro01',
 'oquinky01',
 'ojelese01',
 'okafoja01',
 'okoboel01',
 'okogijo01',
 'okpalkz01',
 'oladivi01',
 'olynyke01',
 'onimi01',
 'osmande01',
 'oubreke01',
 'owensta01',
 'pargoje01',
 'parkeja01',
 'parsoch01',
 'pascher01',
 'pasecan01',
 'pattepa01',
 'pattoju01',
 'paulch01',
 'payneca01',
 'paytoel01',
 'paytoga02',
 'pelleno01',
 'pinsoth01',
 'plumlma01',
 'poeltja01',
 'poirivi01',
 'pondssh01',
 'poolejo01',
 'porteke02',
 'portemi01',
 'porteot01',
 'portibo01',
 'porzikr01',
 'poweldw01',
 'powelno01',
 'princta02',
 'randlch01',
 'randlju01',
 'reavejo02',
 'reddica01',
 'redicjj01',
 'reidna01',
 'richajo01',
 'riverau01',
 'roberan03',
 'robindu01',
 'robingl02',
 'robinje01',
 'robinju01',
 'robinmi01',
 'robyis01',
 'rondora01',
 'rosede01',
 'rosste01',
 'roziete01',
 'rubiori01',
 'russeda01',
 'sabondo01',
 'samanlu01',
 'sampsja02',
 'saricda01',
 'satorto01',
 'schofad01',
 'schrode01',
 'scottmi01',
 'sefolth01',
 'sextoco01',
 'shamela01',
 'shayoma01',
 'shumpim01',
 'siakapa01',
 'silvach01',
 'simmobe01',
 'simonan01',
 'smailal01',
 'smartma01',
 'smithde03',
 'smithis01',
 'smithjr01',
 'smithzh01',
 'snellto01',
 'spellom01',
 'strusma01',
 'sumneed01',
 'swanica01',
 'tatumja01',
 'teaguje01',
 'templga01',
 'theisda01',
 'thomais02',
 'thomakh01',
 'thomala01',
 'thomama02',
 'thomptr01',
 'thornsi01',
 'thybuma01',
 'tollian01',
 'toscaju01',
 'townska01',
 'trentga02',
 'trieral01',
 'tuckepj01',
 'tuckera01',
 'turneev01',
 'turnemy01',
 'uthofja01',
 'valanjo01',
 'valende01',
 'vandeja01',
 'vanvlfr01',
 'vincega01',
 'vonleno01',
 'vucevni01',
 'wadede01',
 'wagnemo01',
 'waitedi01',
 'walkeke02',
 'walkelo01',
 'wallaty01',
 'waltode01',
 'wanambr01',
 'warretj01',
 'washipj01',
 'watanyu01',
 'watertr01',
 'watsopa01',
 'weathqu01',
 'westbru01',
 'whiteco01',
 'whitede01',
 'whiteha01',
 'wiggian01',
 'willigr01',
 'willijo04',
 'willike04',
 'willilo02',
 'willima02',
 'williro04',
 'willini01',
 'willizi01',
 'wilsodj01',
 'winslju01',
 'woodch01',
 'wrighde01',
 'wrighju02',
 'youngth01',
 'youngtr01',
 'zelleco01',
 'zellety01',
 'zizican01',
 'zubaciv01']

In [111]:
data_type = 'play-by-play'
start_year = 2010
years = 2

In [118]:
table_facts = pd.DataFrame({
    'data_type':data_type,
    'start_year':start_year,
    'end_year': start_year + years
    }, index=range(1))

table_facts

      data_type  start_year  end_year
0  play-by-play        2010      2012

In [121]:
table_facts.data_type[0]

'play-by-play'

In [122]:
player_ids

['adamsst01',
 'adebaba01',
 'aldrila01',
 'alexaky01',
 'alexani01',
 'allengr01',
 'allenja01',
 'allenka01',
 'aminual01',
 'anderju01',
 'anderky01',
 'anderry01',
 'antetgi01',
 'antetko01',
 'antetth01',
 'anthoca01',
 'anunoog01',
 'arcidry01',
 'arizatr01',
 'augusdj01',
 'aytonde01',
 'bacondw01',
 'baglema01',
 'balllo01',
 'bambamo01',
 'bareajo01',
 'barneha02',
 'barrerj01',
 'bartowi01',
 'bateske01',
 'batumni01',
 'baynear01',
 'bazemke01',
 'bazleda01',
 'bealbr01',
 'beaslma01',
 'belinma01',
 'belljo01',
 'bembrde01',
 'bendedr01',
 'bertada01',
 'beverpa01',
 'birchkh01',
 'bitadgo01',
 'biyombi01',
 'bjeline01',
 'bledser01',
 'bogdabo01',
 'bogdabo02',
 'bolbo01',
 'boldejo01',
 'boldema01',
 'bonejo01',
 'bongais01',
 'bookede01',
 'bouchch01',
 'bowenbr02',
 'bowmaky01',
 'bradlav01',
 'bradlto01',
 'brantja01',
 'brazdig01',
 'breweco01',
 'bridgmi01',
 'bridgmi02',
 'brissos01',
 'broekry01',
 'brogdma01',
 'brookdi01',
 'brownbr01',
 'brownch02',
 'brownja02',
 'brownmo01',
 'brownst02',
 'browntr01',
 'brunsja01',
 'bryanth01',
 'bullore01',
 'burketr01',
 'burksal01',
 'burtode02',
 'butleji01',
 'cabocbr01',
 'cacokde01',
 'caldwke01',
 'cancavl01',
 'capelca01',
 'carrode01',
 'carteje01',
 'cartevi01',
 'cartewe01',
 'cartemi01',
 'carusal01',
 'caulewi01',
 'chandty01',
 'chandwi01',
 'chealjo01',
 'cheatzy01',
 'chiozch01',
 'chrisma01',
 'clarkga01',
 'clarkbr01',
 'clarkjo01',
 'claxtni01',
 'clemoch01',
 'clevean01',
 'coffeam01',
 'collijo01',
 'colliza01',
 'conlemi01',
 'connapa01',
 'cookqu01',
 'cookty01',
 'covinro01',
 'crabbal01',
 'craigto01',
 'crawfja01',
 'crowdja01',
 'culveja01',
 'curryse01',
 'curryst01',
 'danietr01',
 'davisan02',
 'davised01',
 'daviste02',
 'dedmode01',
 'dellama01',
 'derozde01',
 'diallch01',
 'diallha01',
 'dienggo01',
 'dinwisp01',
 'divindo01',
 'doncilu01',
 'dortlu01',
 'dotsoda01',
 'doumbse01',
 'doziepj01',
 'dragigo01',
 'drumman01',
 'dudleja01',
 'dunnkr01',
 'edwarca01',
 'ellenhe01',
 'ellinwa01',
 'embiijo01',
 'ennisja01',
 'eubandr01',
 'evansja02',
 'exumda01',
 'fallta01',
 'favorde01',
 'feliccr01',
 'fergute01',
 'fernabr01',
 'ferreyo01',
 'finnedo01',
 'forbebr01',
 'fournev01',
 'foxde01',
 'frazime01',
 'frazimi01',
 'fraziti01',
 'fultzma01',
 'gabriwe01',
 'gaffoda01',
 'gallida01',
 'gallola01',
 'garlada01',
 'gasolma01',
 'gayru01',
 'georgpa01',
 'gibsota01',
 'gilesha01',
 'gilgesh01',
 'goberru01',
 'goodwbr01',
 'gordoaa01',
 'gordoer01',
 'grahade01',
 'grahatr01',
 'grantje01',
 'grantje02',
 'grayjo01',
 'greenda02',
 'greendr01',
 'greenja01',
 'greenja02',
 'greenje02',
 'griffbl01',
 'gudurma01',
 'guyky01',
 'hachiru01',
 'hallde01',
 'halldo01',
 'hannadu01',
 'hardati02',
 'hardeja01',
 'harklma01',
 'harpeja01',
 'harremo01',
 'harriga01',
 'harrijo01',
 'harrito02',
 'harrish01',
 'hartjo01',
 'harteis01',
 'hasleud01',
 'hayesja02',
 'haywago01',
 'hensojo01',
 'hernade01',
 'hernaju01',
 'hernawi01',
 'herroty01',
 'herveke01',
 'hezonma01',
 'hieldbu01',
 'hillge01',
 'hillso01',
 'hoardja01',
 'holidaa01',
 'holidjr01',
 'holidju01',
 'holliro01',
 'holmeri01',
 'hoodro01',
 'horfoal01',
 'hortota01',
 'houseda01',
 'howardw01',
 'howarwi01',
 'huertke01',
 'huntede01',
 'hutchch01',
 'ibakase01',
 'iguodan01',
 'ilyaser01',
 'inglejo01',
 'ingrabr01',
 'irvinky01',
 'isaacjo01',
 'iwundwe01',
 'jacksfr01',
 'jacksja02',
 'jacksjo02',
 'jacksju01',
 'jacksre01',
 'jamesju01',
 'jamesle01',
 'jeffeam01',
 'jeffrda01',
 'jeromty01',
 'johnsal02',
 'johnsbj01',
 'johnsca02',
 'johnsja01',
 'johnske04',
 'johnsst04',
 'johnsty01',
 'jokicni01',
 'jonesda03',
 'jonesde02',
 'jonesty01',
 'jordade01',
 'josepco01',
 'kabenmf01',
 'kaminfr01',
 'kanteen01',
 'kennalu01',
 'kiddst01',
 'kiddgmi01',
 'kinglo02',
 'klebima01',
 'knighbr03',
 'knoxke01',
 'konchjo01',
 'korkmfu01',
 'kornelu01',
 'korveky01',
 'kurucro01',
 'kuzmaky01',
 'labissk01',
 'lambje01',
 'langfro01',
 'lavinza01',
 'lawvi01',
 'laymaja01',
 'leaftj01',
 'lecquja01',
 'leeco01',
 'leeda03',
 'lenal01',
 'leonaka01',
 'leoname01',
 'leverca01',
 'lillada01',
 'littlna01',
 'looneke01',
 'lopezbr01',
 'lopezro01',
 'loveke01',
 'lowryky01',
 'luwawti01',
 'lylestr01',
 'maconda01',
 'macurjp01',
 'magetjo01',
 'mahinia01',
 'makerth01',
 'mannte01',
 'marjabo01',
 'markkla01',
 'martica02',
 'martico01',
 'martije02',
 'martike03',
 'masonfr01',
 'mathega01',
 'matthwe02',
 'mbahalu01',
 'mccawpa01',
 'mccolcj01',
 'mccontj01',
 'mcdanja01',
 'mcderdo01',
 'mcgeeja01',
 'mcgruro01',
 'mckinal01',
 'mclaujo01',
 'mclembe01',
 'mcraejo01',
 'mellini01',
 'meltode01',
 'metuch01',
 'middlkh01',
 'mikaer01',
 'milescj01',
 'millema01',
 'millspa02',
 'millspa01',
 'miltosh01',
 'mitchdo01',
 'mitrona01',
 'mokokad01',
 'monkma01',
 'moonema01',
 'mooreet01',
 'moranja01',
 'morgaju01',
 'morrima03',
 'morrima02',
 'morrimo01',
 'motlejo01',
 'mudiaem01',
 'muldemy01',
 'murrade01',
 'murraja01',
 'musadz01',
 'muscami01',
 'mykhasv01',
 'naderab01',
 'nancela02',
 'napiesh01',
 'netora01',
 'newmama01',
 'niangge01',
 'noahjo01',
 'noelne01',
 'norveza01',
 'nowelja01',
 'ntilila01',
 'nunnke01',
 'nurkiju01',
 'nwabada01',
 'onealro01',
 'oquinky01',
 'ojelese01',
 'okafoja01',
 'okoboel01',
 'okogijo01',
 'okpalkz01',
 'oladivi01',
 'olynyke01',
 'onimi01',
 'osmande01',
 'oubreke01',
 'owensta01',
 'pargoje01',
 'parkeja01',
 'parsoch01',
 'pascher01',
 'pasecan01',
 'pattepa01',
 'pattoju01',
 'paulch01',
 'payneca01',
 'paytoel01',
 'paytoga02',
 'pelleno01',
 'pinsoth01',
 'plumlma01',
 'poeltja01',
 'poirivi01',
 'pondssh01',
 'poolejo01',
 'porteke02',
 'portemi01',
 'porteot01',
 'portibo01',
 'porzikr01',
 'poweldw01',
 'powelno01',
 'princta02',
 'randlch01',
 'randlju01',
 'reavejo02',
 'reddica01',
 'redicjj01',
 'reidna01',
 'richajo01',
 'riverau01',
 'roberan03',
 'robindu01',
 'robingl02',
 'robinje01',
 'robinju01',
 'robinmi01',
 'robyis01',
 'rondora01',
 'rosede01',
 'rosste01',
 'roziete01',
 'rubiori01',
 'russeda01',
 'sabondo01',
 'samanlu01',
 'sampsja02',
 'saricda01',
 'satorto01',
 'schofad01',
 'schrode01',
 'scottmi01',
 'sefolth01',
 'sextoco01',
 'shamela01',
 'shayoma01',
 'shumpim01',
 'siakapa01',
 'silvach01',
 'simmobe01',
 'simonan01',
 'smailal01',
 'smartma01',
 'smithde03',
 'smithis01',
 'smithjr01',
 'smithzh01',
 'snellto01',
 'spellom01',
 'strusma01',
 'sumneed01',
 'swanica01',
 'tatumja01',
 'teaguje01',
 'templga01',
 'theisda01',
 'thomais02',
 'thomakh01',
 'thomala01',
 'thomama02',
 'thomptr01',
 'thornsi01',
 'thybuma01',
 'tollian01',
 'toscaju01',
 'townska01',
 'trentga02',
 'trieral01',
 'tuckepj01',
 'tuckera01',
 'turneev01',
 'turnemy01',
 'uthofja01',
 'valanjo01',
 'valende01',
 'vandeja01',
 'vanvlfr01',
 'vincega01',
 'vonleno01',
 'vucevni01',
 'wadede01',
 'wagnemo01',
 'waitedi01',
 'walkeke02',
 'walkelo01',
 'wallaty01',
 'waltode01',
 'wanambr01',
 'warretj01',
 'washipj01',
 'watanyu01',
 'watertr01',
 'watsopa01',
 'weathqu01',
 'westbru01',
 'whiteco01',
 'whitede01',
 'whiteha01',
 'wiggian01',
 'willigr01',
 'willijo04',
 'willike04',
 'willilo02',
 'willima02',
 'williro04',
 'willini01',
 'willizi01',
 'wilsodj01',
 'winslju01',
 'woodch01',
 'wrighde01',
 'wrighju02',
 'youngth01',
 'youngtr01',
 'zelleco01',
 'zellety01',
 'zizican01',
 'zubaciv01']

### Grab Player Data (Height, Country, etc)

In [125]:
url='https://www.basketball-reference.com/players/a/adamsst01.html'
browser.get(url)

In [126]:
html = browser.page_source
soup = bs(html, "html.parser")

In [147]:
results = soup.find_all('span')

In [185]:
results[44].attrs
#height
results[45].attrs
#weight
results[46].attrs
#bday
results[48].attrs
#birthplace
results[49].text
#country code

In [220]:
## Can we get in a df
height = results[44].text
weight = results[45].text
birth_date = results[46].contents[1].text + ", " +results[46].contents[3].text
bplace = results[48].contents[1].text
bplace

'New Zealand'