The Totals, Per 100 Poss, and Advanced pages are fairly similar. Play by Play and Shooting Data have two headers. This Jupyter Notebook will be the testing environment on how to transform the data.

In [1]:
# Import Dependencies
from selenium import webdriver 
import pandas as pd 
from StatPuts import username, password

In [3]:
# Log-in to BKRef
login_address = 'https://stathead.com/users/login.cgi?token=1&redirect_uri=https%3A//www.basketball-reference.com/leagues/NBA_2020_totals.html'
browser = webdriver.Chrome(executable_path=r'chromedriver.exe')
browser.get(login_address)
#Fill in the form with username and password
user_name = browser.find_element_by_id('username')
user_name.send_keys(username)
pass_word = browser.find_element_by_id('password')
pass_word.send_keys(password)
#Click the login button
browser.find_element_by_id('login').submit()

### Test Play-by-Play

In [6]:
url = 'https://www.basketball-reference.com/leagues/NBA_2018_play-by-play.html'
browser.get(url)

In [104]:
year_df = pd.read_html(url)[0]
year_df

    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk             Player                Pos
0                    1       √Ålex Abrines                 SG
1                    2         Quincy Acy                 PF
2                    3       Steven Adams                  C
3                    4        Bam Adebayo                  C
4                    5      Arron Afflalo                 SG
..                 ...                ...                ...
685                537       Tyler Zeller                  C
686                537       Tyler Zeller                  C
687                538        Paul Zipser                 SF
688                539         Ante ≈Ωi≈æiƒá                  C
689                540        Ivica Zubac                  C

    Unnamed: 3_level_0 Unnamed: 4_level_0 Totals       Position Estimate       \
                   Age                 Tm      G    MP               PG%  SG%
0                   24                OKC     75  1134                5%  90%
1                   27                BRK     70  1359               NaN  NaN
2                   24                OKC     76  2487               NaN  NaN
3                   20                MIA     69  1368               NaN  NaN
4                   32                ORL     53   682                5%  77%
..                 ...                ...    ...   ...               ...  ...
685                 28                BRK     42   703               NaN  NaN
686                 28                MIL     24   406               NaN  NaN
687                 23                CHI     54   824               NaN  NaN
688                 21                CLE     32   214               NaN  NaN
689                 20                LAL     43   410               NaN  NaN

          ... +/- Per 100 Poss. Turnovers          Fouls Committed       \
     SF%  ...            On-Off   BadPass LostBall           Shoot Off.
0     5%  ...              -4.4        14        7              66    1
1    NaN  ...               1.8        21       13              63   15
2    NaN  ...               6.8        26       34              75   41
3    NaN  ...              -0.7        16       24              62   18
4    18%  ...              -1.6        10        3              31    4
..   ...  ...               ...       ...      ...             ...  ...
685  NaN  ...               3.8         6       13              42   10
686  NaN  ...               3.6         4        2              30    5
687  51%  ...              -6.5        15       12              38    6
688  NaN  ...              -7.8         3        3              20    2
689  NaN  ...               6.2         8       11              25    5

    Fouls Drawn      Misc.
          Shoot Off.   PGA And1 Blkd
0            15    3    66    4    9
1            20    9   145    1   13
2           112    4   213   32   47
3            81   10   260   19   29
4            11    2    76    0    8
..          ...  ...   ...  ...  ...
685          31    1    72   14   24
686           8    1    46    2   10
687          10    3   115    0   14
688          13    1    12    4    2
689          22    0    58    3   12

[690 rows x 23 columns]

In [105]:
year_df.columns.levels[0]

Index(['+/- Per 100 Poss.', 'Fouls Committed', 'Fouls Drawn', 'Misc.',
       'Position Estimate', 'Totals', 'Turnovers', 'Unnamed: 0_level_0',
       'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Unnamed: 3_level_0',
       'Unnamed: 4_level_0'],
      dtype='object')

In [106]:
year_df.columns = year_df.columns.droplevel()

In [107]:
year_df

,Rk,Player,Pos,Age,Tm,G,MP,PG%,SG%,SF%,...,On-Off,BadPass,LostBall,Shoot,Off.,Shoot,Off.,PGA,And1,Blkd
0,1,√Ålex Abrines,SG,24,OKC,75,1134,5%,90%,5%,...,-4.4,14,7,66,1,15,3,66,4,9
1,2,Quincy Acy,PF,27,BRK,70,1359,NaN,NaN,NaN,...,1.8,21,13,63,15,20,9,145,1,13
2,3,Steven Adams,C,24,OKC,76,2487,NaN,NaN,NaN,...,6.8,26,34,75,41,112,4,213,32,47
3,4,Bam Adebayo,C,20,MIA,69,1368,NaN,NaN,NaN,...,-0.7,16,24,62,18,81,10,260,19,29
4,5,Arron Afflalo,SG,32,ORL,53,682,5%,77%,18%,...,-1.6,10,3,31,4,11,2,76,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,537,Tyler Zeller,C,28,BRK,42,703,NaN,NaN,NaN,...,3.8,6,13,42,10,31,1,72,14,24
686,537,Tyler Zeller,C,28,MIL,24,406,NaN,NaN,NaN,...,3.6,4,2,30,5,8,1,46,2,10
687,538,Paul Zipser,SF,23,CHI,54,824,NaN,NaN,51%,...,-6.5,15,12,38,6,10,3,115,0,14
688,539,Ante ≈Ωi≈æiƒá,C,21,CLE,32,214,NaN,NaN,NaN,...,-7.8,3,3,20,2,13,1,12,4,2
689,540,Ivica Zubac,C,20,LAL,43,410,NaN,NaN,NaN,...,6.2,8,11,25,5,22,0,58,3,12

In [108]:
# Change columns with multiple names (Shoot, Off.)
cols = []
scount, ocount = 1, 1
for column in year_df.columns:
    if column == 'Shoot':
        cols.append(f'Shoot_{scount}')
        scount+=1
        continue
    elif column == 'Off.':
        cols.append(f'Off_{ocount}')
        ocount+=1
        continue
    cols.append(column)
year_df.columns = cols

In [109]:
year_df = year_df.rename(columns={
    'OnCourt':'PMP100_OnCourt',
    'On-Off':'PMP100_On_Off',
    'BadPass': 'BadPassTO',
    'LostBall': 'LostBallTO',
    'Shoot_1': 'FoulC_Shoot',
    'Shoot_2': 'FoulD_Shoot',
    'Off_1': 'FoulC_Off',
    'Off_2': 'FoulD_Off',
})
year_df

,Rk,Player,Pos,Age,Tm,G,MP,PG%,SG%,SF%,...,PMP100_On_Off,BadPassTO,LostBallTO,FoulC_Shoot,FoulC_Off,FoulD_Shoot,FoulD_Off,PGA,And1,Blkd
0,1,√Ålex Abrines,SG,24,OKC,75,1134,5%,90%,5%,...,-4.4,14,7,66,1,15,3,66,4,9
1,2,Quincy Acy,PF,27,BRK,70,1359,NaN,NaN,NaN,...,1.8,21,13,63,15,20,9,145,1,13
2,3,Steven Adams,C,24,OKC,76,2487,NaN,NaN,NaN,...,6.8,26,34,75,41,112,4,213,32,47
3,4,Bam Adebayo,C,20,MIA,69,1368,NaN,NaN,NaN,...,-0.7,16,24,62,18,81,10,260,19,29
4,5,Arron Afflalo,SG,32,ORL,53,682,5%,77%,18%,...,-1.6,10,3,31,4,11,2,76,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,537,Tyler Zeller,C,28,BRK,42,703,NaN,NaN,NaN,...,3.8,6,13,42,10,31,1,72,14,24
686,537,Tyler Zeller,C,28,MIL,24,406,NaN,NaN,NaN,...,3.6,4,2,30,5,8,1,46,2,10
687,538,Paul Zipser,SF,23,CHI,54,824,NaN,NaN,51%,...,-6.5,15,12,38,6,10,3,115,0,14
688,539,Ante ≈Ωi≈æiƒá,C,21,CLE,32,214,NaN,NaN,NaN,...,-7.8,3,3,20,2,13,1,12,4,2
689,540,Ivica Zubac,C,20,LAL,43,410,NaN,NaN,NaN,...,6.2,8,11,25,5,22,0,58,3,12

In [110]:
text_keys = ['Player','Pos','Tm']
keys_list = year_df.keys()
num_keys = []
for key in keys_list:
    if key not in text_keys:
        num_keys.append(key)
year_df = year_df.loc[year_df["Rk"] != "Rk"]

### Need to transfrom Position % to number before converting column data type

In [111]:
perc_list = ["PG%","SG%","SF%","PF%","C%"]
for col in perc_list:
    year_df[col] = pd.to_numeric(year_df[col].replace('\%','',regex=True))/100
    #year_df.loc[:, col] = col_fixer
# pd.to_numeric(year_df["PG%"].replace('\%','',regex=True))/100
# pd.to_numeric(year_df["SG%"].replace('\%','',regex=True))/100
# pd.to_numeric(year_df["SF%"].replace('\%','',regex=True))/100
# pd.to_numeric(year_df["PF%"].replace('\%','',regex=True))/100
# pd.to_numeric(year_df["C%"].replace('\%','',regex=True))/100

<ipython-input-111-f928768182c6>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_df[col] = pd.to_numeric(year_df[col].replace('\%','',regex=True))/100

In [115]:
year_df

,Rk,Player,Pos,Age,Tm,G,MP,PG%,SG%,SF%,...,PMP100_On_Off,BadPassTO,LostBallTO,FoulC_Shoot,FoulC_Off,FoulD_Shoot,FoulD_Off,PGA,And1,Blkd
0,1,√Ålex Abrines,SG,24,OKC,75,1134,0.05,0.90,0.05,...,-4.4,14,7,66,1,15,3,66,4,9
1,2,Quincy Acy,PF,27,BRK,70,1359,NaN,NaN,NaN,...,1.8,21,13,63,15,20,9,145,1,13
2,3,Steven Adams,C,24,OKC,76,2487,NaN,NaN,NaN,...,6.8,26,34,75,41,112,4,213,32,47
3,4,Bam Adebayo,C,20,MIA,69,1368,NaN,NaN,NaN,...,-0.7,16,24,62,18,81,10,260,19,29
4,5,Arron Afflalo,SG,32,ORL,53,682,0.05,0.77,0.18,...,-1.6,10,3,31,4,11,2,76,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,537,Tyler Zeller,C,28,BRK,42,703,NaN,NaN,NaN,...,3.8,6,13,42,10,31,1,72,14,24
686,537,Tyler Zeller,C,28,MIL,24,406,NaN,NaN,NaN,...,3.6,4,2,30,5,8,1,46,2,10
687,538,Paul Zipser,SF,23,CHI,54,824,NaN,NaN,0.51,...,-6.5,15,12,38,6,10,3,115,0,14
688,539,Ante ≈Ωi≈æiƒá,C,21,CLE,32,214,NaN,NaN,NaN,...,-7.8,3,3,20,2,13,1,12,4,2
689,540,Ivica Zubac,C,20,LAL,43,410,NaN,NaN,NaN,...,6.2,8,11,25,5,22,0,58,3,12

In [114]:
for key in num_keys:
    year_df[key] = pd.to_numeric(year_df[key])

<ipython-input-114-c2ca0b14df09>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_df[key] = pd.to_numeric(year_df[key])

year_df.dtype()